game/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :platforms

    resources :vgames do
      resources :reviews, :shallow => true
      resources :guides, :shallow => true
      resources :vgame_platforms, :shallow => true
      resources :topics, :shallow => true do
        resources :posts, :shallow => true
      end
    end

    root 'vgames#index'
  end

game/app/models/vgame.rb
class Vgame < ActiveRecord::Base
  validates :name, :description, :genre, :release,  presence: true
  has_many :guides, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :vgame_platforms, dependent: :destroy
  
  def generate_filename
    string = SecureRandom.hex(20) + ".jpg"
    update fname: string
  end
  
end

game/app/controllers/vgames_controller.rb
class VgamesController < ApplicationController
  before_action :set_vgame, only: [:show, :edit, :update, :destroy]

  #GET /vgames
  def index
    @vgames = Vgame.all
    @platforms = Platform.all
  end

  #GET /vgames/1
  def show
    @admin = true if user_signed_in? && current_user.admin == true else false
    @topics = @vgame.topics.all
    @reviews = @vgame.reviews.all
    @guides = @vgame.guides.all
    @vgame_platforms = @vgame.vgame_platforms.all
    @platforms = Platform.all
    @vgame_platform = VgamePlatform.new
    if File.exist?(Rails.root.join('public', 'games', @vgame.fname))
      @exist = true;
    else
      @exist = false;
    end
  end

  #GET /vgames/new
  def new
    @vgame = Vgame.new
  end

  #GET /vgames/1/edit
  def edit
  end

  #POST /images
  def create
    @vgame = Vgame.new(vgame_params)
    if params[:vgame][:uploaded_file].present?
      @vgame.generate_filename

      @upload_io = params[:vgame][:uploaded_file]
      File.open(Rails.root.join('public', 'games', @vgame.fname), 'wb') do |file|
        file.write(@upload_io.read)
      end

      if @vgame.save
        redirect_to vgame_url(@vgame), notice: 'Game was successfully added.'
      else
        render :new, notice: 'Game failed to add.'
      end
    else
      render :new, notice: 'Game failed to add.'
    end
  end

  #PATCH/PUT /vgames/1
  def update
    if params[:vgame][:uploaded_file].present?
      File.delete(Rails.root.join('public', 'games', @vgame.fname))
      @vgame.generate_filename

      @upload_io = params[:vgame][:uploaded_file]
      File.open(Rails.root.join('public', 'games', @vgame.fname), 'wb') do |file|
        file.write(@upload_io.read)
      end
    end
    if @vgame.update(update_params)
      redirect_to vgame_url(@vgame), notice: 'Game was successfully updated.'
    else
      render :edit, notice: 'Game failed to update.'
    end
  end

  #DELETE /vgames/1
  def destroy
    @vgame.destroy
    redirect_to vgames_path, notice: 'Game was removed.'
  end
  private
  def set_vgame
    @vgame = Vgame.find(params[:id])
  end

  def vgame_params
    params.require(:vgame).permit(:name, :genre, :developer, :release, :description, :fname)
  end

  def update_params
    params.require(:vgame).permit(:name, :genre, :developer, :release, :description)
  end
end

game/app/views/vgames/_form.html.erb
<%= form_for(@vgame) do |f| %>
  <%if @vgame.errors.any?%>
        <div id = "error_explanation">
        <h2>%= pluralize(@vgame.errors.count, "error") %> prohibited this vgame from being saved:</h2>
        <ul>
          <% @vgame.errors.full_messages.each do |message| %>
            <li><%=message%></li>
        <%end%>
        </ul>
      </div>
    <%end%>
      <br>
      <div class="field">
        <%= f.file_field :uploaded_file, class: 'myButton'%>
      </div>
      <br>
      <div class="field">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'textbox'%>
      </div>
      <br>
      <div class="field">
        <%= f.label :genre%>
        <%= f.text_field :genre, class: 'textbox'%>
      </div>
      <br>
      <div class="field">
        <%= f.label :developer%>
        <%= f.text_field :developer, class: 'textbox'%>
      </div>
      <br>
      <div class="field">
        <%= f.label :release%>
        <%= f.date_field :release, class: 'datebox'%>
      </div>
      <br>
      <div class="field">
        <%= f.label :description%>
        <%= f.text_area :description, size: "150x10", class: 'textbox'%>
      </div>
      <br>
      <div class="actions">
        <%= f.submit class: 'mybutton' %>
      </div>
    <%end%>

game/app/views/vgames/edit.html.erb
<h2>Edit <%=@vgame.name%></h2>
<%= render 'form' %>
<br>
<b>Remove Platform</b>
<ul>
  <% @vgame.vgame_platforms.each do |vplat|%>
  <li> <%= link_to vplat.platform.name, vplat, method: :delete, data: {confirm: 'Are you sure?'}%></li>
<%end%>
  </ul>
<%= link_to "Back to #{@vgame.name}", @vgame %> 

game/app/views/vgames/index.html.erb
<% x = 2%>
  <div id = "tabs">
<ul>
  <li><a href= "#tabs-1">all</a></li>
  <% @platforms.each do |platform|%>
    <li><a href= <%="#tabs-#{x}"%>><%=platform.name%></a></li>
    <% x = x+1%>
  <%end%>
</ul>
<div id = "tabs-1">  
<table id = "games">
  <% @vgames.each do |vgame| %>
  <tr>
    <td><%=link_to vgame.name, vgame%></td>
  </tr>
<%end%>
</table>
</div>
<% x = 2%>
<%@platforms.each do |platform|%>
  <div id = <%="tabs-#{x}"%>>  
    <% x = x+1 %>
<table id = "games">
  <% platform.vgame_platforms.each do |vgame_platform| %>
  <tr>
    <td><%=link_to vgame_platform.vgame.name, vgame_platform.vgame%></td>
  </tr>
<%end%>
</table>
</div>
<%end%>
<br>
</div>
<%if @admin%>
  <%= link_to 'Add a Game', new_vgame_path %>
<%end%>

game/app/views/vgames/new.html.erb
<h2>Add a Game</h2>
<%= render 'form' %>
<br>
<%= link_to "Back to all games", vgames_path %> 

game/app/views/vgames/show.html.erb
<%= javascript_include_tag "assets/javascripts/show"%>
<title><%=@vgame.name%></title>
<body>
<p id = "info""">
<div id = image>
<%if @exist%>
    <%= image_tag(root_url + "/games/" + @vgame.fname, size: "200x200", alt: @vgame.fname)%>
  <%else%>
    <%= image_tag(root_url+"/games/default.jpg", size: "100x100", alt: "default.jpg")%>
  <%end%>
</div>
<br>
<br>
<p>
<%= @vgame.name %>
</p>
<p>
<%@vgame_platforms.each do |vgame_platform|%>
  <%=vgame_platform.platform.name%>
<%end%>
</p>
<%= "Developed by #{@vgame.developer}"%>
<br>
<br>
<%= @vgame.release.strftime("released on %m/%d/%Y")%>
<br>
<br>
<br>
</p>
<div id= "tabs">
<ul>
  <li><a href="#tabs-1">Info</a></li>
  <li><a href="#tabs-2">Reviews</a></li>
  <li><a href="#tabs-3">Guides</a></li>
  <li><a href="#tabs-4">Forums</a></li>
</ul>
<div id = "tabs-1">
  <p>
  <%= @vgame.description %>
  <p>
</div>
<div id = "tabs-2">
  <table>
    <% @reviews.each do |review| %>
      <tr>
      <td><%=link_to review.title, review%></td>
      <td><%=review.user.name%></td>
      <td><%= (review.updated_at.in_time_zone("Pacific Time (US & Canada)")).to_time.strftime('%B %e at %l:%M %p')%></td>
      <%if (current_user == review.user || @admin)%>
        <td><%=link_to 'Edit', edit_review_path(review)%> </td>
        <td><%=link_to 'Remove', review, method: :delete, data: {confirm: 'Are You Sure?'}%></td>
    <%end%>
    </tr>
  <%end%>
    <%if user_signed_in? %>
      <tr>
      <td><%=link_to 'Create New Review', new_vgame_review_path(@vgame)%>
    </tr>
    <%end%>
    </table>
  </div>
  <div id = "tabs-3">
    <table>
      <% @guides.each do |guide| %>
        <tr>
        <td><%=link_to guide.title, guide%></td>
        <td><%=guide.user.name%></td>
        <td><%=(guide.updated_at.in_time_zone("Pacific Time (US & Canada)")).to_time.strftime('%B %e at %l:%M %p')%></td>
      <%if (current_user == guide.user || @admin)%>
        <td><%=link_to 'Edit', edit_guide_path(guide)%> </td>
        <td><%=link_to 'Remove', guide, method: :delete, data: {confirm: 'Are You Sure?'}%></td>
    <%end%>
      </tr>
    <%end%>
      <%if user_signed_in? %>
        <tr>
        <td><%=link_to 'Create New Guide', new_vgame_guide_path(@vgame)%>
      </tr>
      <%end%>
      </table>
    </div>
    <div id = "tabs-4">
      <table>
        <% @topics.each do |topic| %>
          <tr>
          <td><%=link_to topic.title, topic%></td>
          <td><%=topic.user.name%></td>
          <td><%=(topic.updated_at.in_time_zone("Pacific Time (US & Canada)")).to_time.strftime('%B %e at %l:%M %p')%></td>
      <%if (current_user == topic.user || @admin)%>
        <td><%=link_to 'Edit', edit_topic_path(topic)%> </td>
        <td><%=link_to 'Remove', topic, method: :delete, data: {confirm: 'Are You Sure?'}%></td>
        </tr>
    <%end%>
      <%end%>
        <%if user_signed_in? %>
          <tr>
          <td><%=link_to 'Create New Forum Topic', new_vgame_topic_path(@vgame)%>
        </tr>
        <%end%>
      </table>
</div>
      <%if (@admin)%>
        <p>Add Platforms</p>
         <%=render "vgame_platforms/form"%>
        <%=link_to 'Edit this game', edit_vgame_path(@vgame)%> </td>
      <%=link_to 'Remove this game', @vgame, method: :delete, data: {confirm: 'Are You Sure?'}%></td>
  <%end%>
</div>
      </body>